version: "3.9"

name: zk-steam-proto

services:
  db:
    image: postgres:16-alpine
    container_name: zksteam_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  ollama:
    image: ollama/ollama:latest
    container_name: zksteam_ollama
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_MAX_LOADED_MODELS: 1
      OLLAMA_HOST: 0.0.0.0:11434
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - appnet

  ollama-init:
    image: ollama/ollama:latest
    container_name: zksteam_ollama_init
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: ${OLLAMA_MODEL}
    entrypoint: ["/bin/sh","-lc"]
    command: >
      "until curl -fsS http://ollama:11434/api/tags >/dev/null; do echo waiting for ollama; sleep 2; done;
      echo pulling $${OLLAMA_MODEL};
      ollama pull $${OLLAMA_MODEL} || true;
      echo done"
    networks:
      - appnet
    profiles: ["init"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zksteam_backend
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - backend-node-modules:/usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zksteam_frontend
    env_file: .env
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - frontend-node-modules:/usr/src/app/node_modules
    depends_on:
      backend:
        condition: service_started
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: zksteam_nginx
    profiles: ["nginx"]
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

volumes:
  db-data:
  ollama-models:
  backend-node-modules:
  frontend-node-modules:

networks:
  appnet:
    driver: bridge

